apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: commander-hpa
  namespace: ops-commander
  labels:
    app: commander-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: commander-api-deployment
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 15
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
